name: Publish Nuget packages

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0'
  PACKAGE_VERSION: "0.3.1"

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: dotnet restore Firepuma.EventMediation.IntegrationEvents
      - run: dotnet restore Firepuma.EventMediation.IntegrationEvents.CommandExecution
      - run: dotnet restore Firepuma.EventMediation.Tests

      - run: dotnet test --no-restore

      - run: dotnet pack Firepuma.EventMediation.IntegrationEvents/Firepuma.EventMediation.IntegrationEvents.csproj --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }}
      - run: dotnet pack Firepuma.EventMediation.IntegrationEvents.CommandExecution/Firepuma.EventMediation.IntegrationEvents.CommandExecution.csproj --configuration Release --output . -p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
